export const competions = [
  {
    analytics_identifier: 'Postcards from Summer Camp Contest',
    displayed_location: {
      icon: 'globe',
      location: 'Online',
    },
    eligibility_requirement_invite_only_description: null,
    featured: false,
    id: 1,
    invite_only: false,
    managed_by_devpost_badge: false,
    open_state: 'open',
    organization_name: 'Gotham Writers',
    prize_amount: 'Free Gotham class',
    registrations_count: null,
    start_a_submission_url: 'https://gothamwriters.com/contests/postcards-from-summer-camp',
    submission_gallery_url: null,
    submission_period_dates: 'Open',
    themes: [
      { name: 'Creative Writing', description: 'Capture the essence of summer camp experiences' },
    ],
    thumbnail_url: '../../public/images/competitions/IMG-20240831-WA0011.jpg',
    time_left_to_submission: 'about 1 month left',
    title: 'Postcards from Summer Camp Contest',
    url: 'https://gothamwriters.com/contests/postcards-from-summer-camp',
    winners_announced: false,
  },
  {
    analytics_identifier: 'Essay Contest 2024 by Competition Success Review Magazine',
    displayed_location: {
      icon: 'globe',
      location: 'Online',
    },
    eligibility_requirement_invite_only_description: null,
    featured: false,
    id: 2,
    invite_only: false,
    managed_by_devpost_badge: false,
    open_state: 'open',
    organization_name: 'Competition Success Review Magazine',
    prize_amount: 'Certificate of Merit plus Study Material, Pens, Deodorant Body Spray',
    registrations_count: null,
    start_a_submission_url: 'https://csrmagazine.in/essay-contest-2024',
    submission_gallery_url: null,
    submission_period_dates: 'Open',
    themes: [
      { name: 'Monthly Topics', description: 'Topics announced every month for essay submissions' },
    ],
    thumbnail_url: '../../public/images/competitions/IMG-20240831-WA0012.jpg',
    time_left_to_submission: 'about 2 weeks left',
    title: 'Essay Contest 2024 by Competition Success Review Magazine',
    url: 'https://csrmagazine.in/essay-contest-2024',
    winners_announced: false,
  },
  {
    analytics_identifier: 'IGBC Green Your School Programme 2024',
    displayed_location: {
      icon: 'globe',
      location: 'Online',
    },
    eligibility_requirement_invite_only_description: null,
    featured: false,
    id: 3,
    invite_only: false,
    managed_by_devpost_badge: false,
    open_state: 'open',
    organization_name: 'Indian Green Building Council',
    prize_amount: '₹3,00,000 for top 3 finalists, ₹2,25,000 for next 5 finalists',
    registrations_count: null,
    start_a_submission_url: 'https://igbc.in/green-your-school',
    submission_gallery_url: null,
    submission_period_dates: 'Open',
    themes: [{ name: 'Green Initiatives', description: 'Ideas to make schools more eco-friendly' }],
    thumbnail_url: '../../public/images/competitions/IMG-20240831-WA0013.jpg',
    time_left_to_submission: 'about 2 weeks left',
    title: 'IGBC Green Your School Programme 2024',
    url: 'https://igbc.in/green-your-school',
    winners_announced: false,
  },
  {
    analytics_identifier: 'Atlas Shrugged Essay Contest by Ayn Rand Institute',
    displayed_location: {
      icon: 'globe',
      location: 'Online',
    },
    eligibility_requirement_invite_only_description: null,
    featured: false,
    id: 4,
    invite_only: false,
    managed_by_devpost_badge: false,
    open_state: 'open',
    organization_name: 'Ayn Rand Institute',
    prize_amount: 'Total prize amount worth Rs. 25L+ / $31000',
    registrations_count: null,
    start_a_submission_url: 'https://aynrand.org/atlas-shrugged-essay-contest',
    submission_gallery_url: null,
    submission_period_dates: 'Open',
    themes: [
      { name: 'Philosophical Essays', description: 'Engage with Rand’s ideas through her novels' },
    ],
    thumbnail_url: '../../public/images/competitions/IMG-20240831-WA0014.jpg',
    time_left_to_submission: 'about 3 weeks left',
    title: 'Atlas Shrugged Essay Contest by Ayn Rand Institute',
    url: 'https://aynrand.org/atlas-shrugged-essay-contest',
    winners_announced: false,
  },
  {
    analytics_identifier: 'Inspire-Manak Awards 2024 by DST with National Innovation Foundation',
    displayed_location: {
      icon: 'globe',
      location: 'Online',
    },
    eligibility_requirement_invite_only_description: null,
    featured: false,
    id: 5,
    invite_only: false,
    managed_by_devpost_badge: false,
    open_state: 'open',
    organization_name: 'Department of Science & Technology',
    prize_amount: 'INR 10,000',
    registrations_count: null,
    start_a_submission_url: 'https://dst.gov.in/inspire-manak-awards',
    submission_gallery_url: null,
    submission_period_dates: 'Open',
    themes: [{ name: 'Science & Innovation', description: 'Encouraging innovation in science' }],
    thumbnail_url: '../../public/images/competitions/IMG-20240831-WA0015.jpg',
    time_left_to_submission: 'about 2 weeks left',
    title: 'Inspire-Manak Awards 2024 by DST with National Innovation Foundation',
    url: 'https://dst.gov.in/inspire-manak-awards',
    winners_announced: false,
  },
  {
    analytics_identifier: 'Fountainhead Essay Contest by Ayn Rand Institute',
    displayed_location: {
      icon: 'globe',
      location: 'Online',
    },
    eligibility_requirement_invite_only_description: null,
    featured: false,
    id: 6,
    invite_only: false,
    managed_by_devpost_badge: false,
    open_state: 'open',
    organization_name: 'Ayn Rand Institute',
    prize_amount: 'Total prize amount worth Rs. 25L+ / $31000',
    registrations_count: null,
    start_a_submission_url: 'https://aynrand.org/fountainhead-essay-contest',
    submission_gallery_url: null,
    submission_period_dates: 'Open',
    themes: [
      { name: 'Philosophical Essays', description: 'Engage with Rand’s ideas through her novels' },
    ],
    thumbnail_url: '../../public/images/competitions/IMG-20240831-WA0016.jpg',
    time_left_to_submission: 'about 3 weeks left',
    title: 'Fountainhead Essay Contest by Ayn Rand Institute',
    url: 'https://aynrand.org/fountainhead-essay-contest',
    winners_announced: false,
  },
  {
    analytics_identifier: 'Pratibha Sangam Competition 2024',
    displayed_location: {
      icon: 'globe',
      location: 'Online',
    },
    eligibility_requirement_invite_only_description: null,
    featured: false,
    id: 7,
    invite_only: false,
    managed_by_devpost_badge: false,
    open_state: 'open',
    organization_name: 'ICCR',
    prize_amount: 'Total prize amount worth Rs. 90k, travel and stay expenses covered',
    registrations_count: null,
    start_a_submission_url: 'https://iccr.gov.in/pratibha-sangam-competition',
    submission_gallery_url: null,
    submission_period_dates: 'Open',
    themes: [
      {
        name: 'Classical Indian Music and Dance',
        description: 'Global competition for performers',
      },
    ],
    thumbnail_url: '../../public/images/competitions/IMG-20240831-WA0017.jpg',
    time_left_to_submission: 'about 1 week left',
    title: 'Pratibha Sangam Competition 2024',
    url: 'https://iccr.gov.in/pratibha-sangam-competition',
    winners_announced: false,
  },
]
